[project]
name = "kernelvulnauditp"
version = "0.1.0"
description = "This tool checks the practical functionality of linux kernel exploits"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet>=0.80.5",
]

